/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.upb.tresenraya;

import edu.upb.tresenraya.aula.InterfazCompra;
import edu.upb.tresenraya.Comando.Comando;
import edu.upb.tresenraya.Comando.MarcarSimbolo;
import edu.upb.tresenraya.Comando.NuevaPartida;
import edu.upb.tresenraya.Comando.SolicitudConexion;
import edu.upb.tresenraya.db.ConexionDb;
import edu.upb.tresenraya.mediador.Mediador;
import edu.upb.tresenraya.server.ServidorJuego;
import javax.swing.JLabel;
import edu.upb.tresenraya.mediador.OnMessageListener;
import edu.upb.tresenraya.logicaTicTacToe;
import edu.upb.tresenraya.server.SocketClient;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author rlaredo
 */
public class TresEnRayaUI extends javax.swing.JFrame implements OnMessageListener, ActionListener{

    private ServidorJuego servidorJuego;
    private InterfazCompra interfazCompra;
    private logicaTicTacToe logica = new logicaTicTacToe();
    private SocketClient socketClient;

    /**
     * Creates new form TresEnRayaUI
     */
    public TresEnRayaUI() {
        initComponents();
        Mediador.addListener(this);
        this.enviarMensaje.addActionListener(this);
        this.btnConectar.addActionListener(this);
//        this.enviarMensaje.setText("<b>Hola</>");
//        this.iconoDeIsaac.setIcon(new ImageIcon ());
        ConexionDb.instancia().getConnection();
    }
    
    public JLabel getLabel(){
        return this.jlMessage;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnServer = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jlMessage = new javax.swing.JLabel();
        enviarMensaje = new javax.swing.JButton();
        btnConectar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        canvas1 = new java.awt.Canvas();
        grilla00 = new java.awt.Button();
        grilla01 = new java.awt.Button();
        grilla02 = new java.awt.Button();
        grilla12 = new java.awt.Button();
        grilla10 = new java.awt.Button();
        grilla11 = new java.awt.Button();
        grilla20 = new java.awt.Button();
        grilla21 = new java.awt.Button();
        grilla22 = new java.awt.Button();
        jScrollPane2 = new javax.swing.JScrollPane();
        chat = new javax.swing.JTextArea();
        textoIP = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        mandarMensaje = new javax.swing.JTextField();
        btnReinicio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnServer.setText("Iniciar Servidor");
        btnServer.setFocusable(false);
        btnServer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnServer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServerActionPerformed(evt);
            }
        });
        jToolBar1.add(btnServer);

        jButton2.setText("Iniciar conexion");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jSplitPane1.setDividerLocation(500);

        jlMessage.setText("Inicio de chat");

        enviarMensaje.setText("Enviar");
        enviarMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarMensajeActionPerformed(evt);
            }
        });

        btnConectar.setText("Conectar");
        btnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarActionPerformed(evt);
            }
        });

        jButton1.setText("Compra Premium ahora");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        grilla00.setLabel("_");
        grilla00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grilla00ActionPerformed(evt);
            }
        });

        grilla01.setLabel("_");
        grilla01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grilla01ActionPerformed(evt);
            }
        });

        grilla02.setLabel("_");
        grilla02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grilla02ActionPerformed(evt);
            }
        });

        grilla12.setLabel("_");
        grilla12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grilla12ActionPerformed(evt);
            }
        });

        grilla10.setLabel("_");
        grilla10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grilla10ActionPerformed(evt);
            }
        });

        grilla11.setLabel("_");
        grilla11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grilla11ActionPerformed(evt);
            }
        });

        grilla20.setLabel("_");
        grilla20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grilla20ActionPerformed(evt);
            }
        });

        grilla21.setLabel("_");
        grilla21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grilla21ActionPerformed(evt);
            }
        });

        grilla22.setLabel("_");
        grilla22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grilla22ActionPerformed(evt);
            }
        });

        chat.setColumns(20);
        chat.setRows(5);
        jScrollPane2.setViewportView(chat);

        textoIP.setText("localhost");
        textoIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoIPActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingresa la IP de un compañero");

        mandarMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mandarMensajeActionPerformed(evt);
            }
        });

        btnReinicio.setText("Reset button");
        btnReinicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReinicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(grilla22, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grilla21, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textoIP, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(11, 11, 11))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(btnConectar)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(grilla02, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(grilla01, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(grilla00, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(grilla10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(grilla12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(grilla11, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(37, 37, 37)
                        .addComponent(grilla20, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnReinicio))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jlMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mandarMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enviarMensaje))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(grilla00, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grilla10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(grilla01, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(grilla11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(grilla02, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(grilla12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(grilla21, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(grilla22, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(grilla20, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReinicio))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(jlMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnConectar)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mandarMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enviarMensaje))
                .addGap(17, 17, 17)
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Amina", "Ariana", "Fernando Rodriguez", "Josue Parada", "Miguel Acha" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jSplitPane1.setRightComponent(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServerActionPerformed
                if (servidorJuego == null) {
            try {
                servidorJuego = new ServidorJuego();
                servidorJuego.start();
                btnServer.setText("Servidor Iniciado");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnServerActionPerformed

    private void enviarMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarMensajeActionPerformed
        // TODO add your handling code here:
        if (mandarMensaje.getText().equals("y")) {
            this.chat.setText(this.chat.getText()+System.lineSeparator()+"Conexiones pendientes aceptadas.");
            servidorJuego.client.send(("0003|NICOLAS CRESPO Host"+System.lineSeparator()).getBytes());
            //esto es nulo wn
            //socketClient.send(("0003|NICOLAS CRESPO H23".getBytes()));
        }
        else if (mandarMensaje.getText().equals("n")) {
            this.chat.setText(this.chat.getText()+System.lineSeparator()+"Conexion rechazada y socketClient de SERVIDORJUEGO establecido a nulo.");
            servidorJuego.client.send(("0002"+ System.lineSeparator()).getBytes()); 
            servidorJuego = null; 
           socketClient = null;
            btnServer.setText("Iniciar Servidor");
//            socketClient.send(("0002".getBytes()));
            
        }
        else {
            this.chat.setText(this.chat.getText()+System.lineSeparator()+mandarMensaje.getText());
            if (socketClient!=null) {
                socketClient.send((mandarMensaje.getText() + System.lineSeparator()).getBytes());
            }
            if (servidorJuego!=null) {
                servidorJuego.client.send((mandarMensaje.getText() + System.lineSeparator()).getBytes());
            }
            
        }
       
       mandarMensaje.setText("");
    }//GEN-LAST:event_enviarMensajeActionPerformed

    private void btnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarActionPerformed
        // TODO add your handling code here:
        //ahora si en este esta el crear cliente
        if (socketClient == null) {
            try {
                //Socket(ip,puerto)
                socketClient = new SocketClient(new Socket(textoIP.getText(),1825));
                socketClient.start();
                SolicitudConexion solicitudAEnviar = new SolicitudConexion("NICOLAS CRESPO");
                //0001 es el codigo de solicitud enviada
                socketClient.send(solicitudAEnviar.getComando().getBytes());
//                BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
                System.out.println("Escriba un mensaje por la caja de texto.");
                chat.setText(chat.getText()+System.lineSeparator()+"Nueva conexion establecida con "+textoIP.getText()+" exitosamente!");
//                socketClient.send((br.readLine() + System.lineSeparator()).getBytes());
//                String[] args = {textoIP.getText()};
//                SocketClient.main(args);
//                jButton2.setText("Cliente Iniciado");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnConectarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jPanel1.setBackground(Color.green);
        if (interfazCompra == null) {
            try {
                interfazCompra = new InterfazCompra();
//                btnServer.setText("Servidor Iniciado");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void logicaBotonPresionado(int valorX, int valorY) {
        
        if (socketClient!=null) {
            socketClient.send(("0008|"+logica.turnoActual+"|"+valorX+"|"+valorY + System.lineSeparator()).getBytes());
        }
        if (servidorJuego!=null) {
            servidorJuego.client.send(("0008|"+logica.turnoActual+"|"+valorX+"|"+valorY + System.lineSeparator()).getBytes());
        }
        logica.setGrilla(valorX,valorY,logica.turnoActual);
        if (logica.winner!="")
            victoria();
    }
    private void grilla00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grilla00ActionPerformed
        // TODO add your handling code here:
        int valorX = 0;
        int valorY = 0;
        logicaBotonPresionado(valorX,valorY);
        grilla00.setLabel(logica.grilla[valorX][valorY]);
    }//GEN-LAST:event_grilla00ActionPerformed

    private void grilla01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grilla01ActionPerformed
        int valorX = 0;
        int valorY = 1;
        logicaBotonPresionado(valorX,valorY);
        grilla01.setLabel(logica.grilla[valorX][valorY]);
    }//GEN-LAST:event_grilla01ActionPerformed

    private void grilla02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grilla02ActionPerformed
        int valorX = 0;
        int valorY = 2;
        logicaBotonPresionado(valorX,valorY);
        grilla02.setLabel(logica.grilla[valorX][valorY]);
    }//GEN-LAST:event_grilla02ActionPerformed

    private void grilla12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grilla12ActionPerformed
        int valorX = 1;
        int valorY = 2;
        logicaBotonPresionado(valorX,valorY);
        grilla12.setLabel(logica.grilla[valorX][valorY]);
    }//GEN-LAST:event_grilla12ActionPerformed

    private void grilla10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grilla10ActionPerformed
        int valorX = 1;
        int valorY = 0;
        logicaBotonPresionado(valorX,valorY);
        grilla10.setLabel(logica.grilla[valorX][valorY]);
    }//GEN-LAST:event_grilla10ActionPerformed

    private void grilla11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grilla11ActionPerformed
        int valorX = 1;
        int valorY = 1;
        logicaBotonPresionado(valorX,valorY);
        grilla11.setLabel(logica.grilla[valorX][valorY]);
    }//GEN-LAST:event_grilla11ActionPerformed

    private void grilla20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grilla20ActionPerformed
        int valorX = 2;
        int valorY = 0;
        logicaBotonPresionado(valorX,valorY);
        grilla20.setLabel(logica.grilla[valorX][valorY]);
    }//GEN-LAST:event_grilla20ActionPerformed

    private void grilla21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grilla21ActionPerformed
        int valorX = 2;
        int valorY = 1;
        logicaBotonPresionado(valorX,valorY);
        grilla21.setLabel(logica.grilla[valorX][valorY]);
    }//GEN-LAST:event_grilla21ActionPerformed

    private void grilla22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grilla22ActionPerformed
        int valorX = 2;
        int valorY = 2;
        logicaBotonPresionado(valorX,valorY);
        grilla22.setLabel(logica.grilla[valorX][valorY]);
    }//GEN-LAST:event_grilla22ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
//        if (Socketc == null) {
//            try {
//                SocketClient.main(new String[0]);
//                jButton2.setText("Cliente Iniciado");
//            } catch (Exception e) {
//                e.printStackTrace();
//            }
//        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void textoIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoIPActionPerformed

    private void mandarMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mandarMensajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mandarMensajeActionPerformed

    private void btnReinicioPressed() {
        grilla00.setLabel("_");
        grilla01.setLabel("_");
        grilla02.setLabel("_");
        grilla10.setLabel("_");
        grilla11.setLabel("_");
        grilla12.setLabel("_");
        grilla20.setLabel("_");
        grilla21.setLabel("_");
        grilla22.setLabel("_");
        logica.setTurnoActual("X");
        logica.grilla=new String[3][3];
        //Mandamos solicitud de nueva partida
        servidorJuego.client.send(("0007"+System.lineSeparator()).getBytes());
//        logica.setGrilla(0, 0, "_");
//        logica.setGrilla(0, 1, "_");
//        logica.setGrilla(0, 2, "_");
//        logica.setGrilla(1, 0, "_");
//        logica.setGrilla(1, 1, "_");
//        logica.setGrilla(1, 2, "_");
//        logica.setGrilla(2, 0, "_");
//        logica.setGrilla(2, 1, "_");
//        logica.setGrilla(2, 2, "_");
    }
    private void btnReinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReinicioActionPerformed
        // TODO add your handling code here:
        btnReinicioPressed();
    }//GEN-LAST:event_btnReinicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TresEnRayaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TresEnRayaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TresEnRayaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TresEnRayaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TresEnRayaUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConectar;
    private javax.swing.JButton btnReinicio;
    private javax.swing.JButton btnServer;
    private java.awt.Canvas canvas1;
    private javax.swing.JTextArea chat;
    private javax.swing.JButton enviarMensaje;
    private java.awt.Button grilla00;
    private java.awt.Button grilla01;
    private java.awt.Button grilla02;
    private java.awt.Button grilla10;
    private java.awt.Button grilla11;
    private java.awt.Button grilla12;
    private java.awt.Button grilla20;
    private java.awt.Button grilla21;
    private java.awt.Button grilla22;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel jlMessage;
    private javax.swing.JTextField mandarMensaje;
    private javax.swing.JTextField textoIP;
    // End of variables declaration//GEN-END:variables

    
            
    @Override
    public void onMessage(String msg) {

        try {
            SolicitudConexion solicitud = new SolicitudConexion();
            solicitud.parsear(msg);
            
            if (solicitud.nombre!=null) {
            this.chat.setText(this.chat.getText()+System.lineSeparator()+"El usuario "+solicitud.nombre+" ha intentado conectarse. Aceptas? y/n.");
        } else {
                this.chat.setText(this.chat.getText()+System.lineSeparator()+msg);
                Thread.sleep(400);
            }
            
        } catch (InterruptedException ex) {
            Logger.getLogger(TresEnRayaUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void onClose() {
        System.out.println("UI: Cayo el cliente");        
    }
    
    public void onButtonGreen() {
        jPanel1.setBackground(Color.green);
//        this.btnClase.setText();
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        System.out.println("a: "+e.getActionCommand());
    }

    private void victoria() {
        if (logica.winner=="X") {
            grilla00.setBackground(Color.orange);
            grilla01.setBackground(Color.orange);
            grilla02.setBackground(Color.orange);
            grilla10.setBackground(Color.orange);
            grilla11.setBackground(Color.orange);
            grilla12.setBackground(Color.orange);
            grilla20.setBackground(Color.orange);
            grilla21.setBackground(Color.orange);
            grilla22.setBackground(Color.orange);
        }
        if (logica.winner=="O") {
            grilla00.setBackground(Color.cyan);
            grilla01.setBackground(Color.cyan);
            grilla02.setBackground(Color.cyan);
            grilla10.setBackground(Color.cyan);
            grilla11.setBackground(Color.cyan);
            grilla12.setBackground(Color.cyan);
            grilla20.setBackground(Color.cyan);
            grilla21.setBackground(Color.cyan);
            grilla22.setBackground(Color.cyan);
        }
    }

    public void onMessage(Object c) {
        return;
    }

    @Override
    public void onMessage(Comando c) {
        // tambien se puede hacer (c instanceof MarcarSimbolo)
        if (c.getClass()==MarcarSimbolo.class) {
            MarcarSimbolo c2 = (MarcarSimbolo) c;
            logica.setGrilla(c2.valorX,c2.valorY,c2.simbolo);
            chat.setText(chat.getText()+System.lineSeparator()+c.comando);
            switch(c2.valorX) {
                case 0:
                    switch (c2.valorY) {
                        case 0:
                            grilla00.setLabel(c2.simbolo);
                            break;
                        case 1:
                            grilla01.setLabel(c2.simbolo);
                            break;
                        case 2:
                            grilla02.setLabel(c2.simbolo);
                            break;
                    }
                    break;
                case 1:
                    switch (c2.valorY) {
                        case 0:
                            grilla10.setLabel(c2.simbolo);
                            break;
                        case 1:
                            grilla11.setLabel(c2.simbolo);
                            break;
                        case 2:
                            grilla12.setLabel(c2.simbolo);
                            break;
                    }
                    break;
                    
                case 2:
                    switch (c2.valorY) {
                        case 0:
                            grilla20.setLabel(c2.simbolo);
                            break;
                        case 1:
                            grilla21.setLabel(c2.simbolo);
                            break;
                        case 2:
                            grilla22.setLabel(c2.simbolo);
                            break;
                    }
                    break;
            }
//            logica.setTurnoActual(logica.cambiaTurnos(logica.turnoActual));
            if (logica.winner!="")
                victoria();
            
                
                    
        }
        if (c.getClass()==SolicitudConexion.class) {
            SolicitudConexion c2 = (SolicitudConexion) c;
            SolicitudConexionUI scui = new SolicitudConexionUI(c2.nombre);
            System.out.println("Estoy en la linea 675");
        }
        if (c.getClass()==NuevaPartida.class) {
            NuevaPartida c2 = (NuevaPartida) c;
            btnReinicioPressed();
        }
    }
}
